### ISSUE TITLE
Inference api error: Service Unavailable

### ISSUE THREAD

**Issue by vanschroeder** [huggingface/llm-vscode#137] opened 2024-04-16 17:14 UTC
I am unable to make any use of llm-vscode. I get nothing but error messages, first I get `Inference api error: Service Unavailable`, and then with `http error: builder error: relative URL without a base` this seems like broken settings, but I have gone so far as to read the docs and try manually setting the `llm.url` setting to no avail, best I get is a "Service Unavailable" again and have just gone through a complete deletion of VSCode and it's settings files under the Application Support dir and a reboot + reinstall only to get this all over again. 

llm-vscode was working at one point, but can no longer use it and Google search regarding these errors only points to some Rust issues in other projects, and the errors presented in VSCode are of no help at all. Anyway, posting this here and uninstalling the plugin to find other solutions. Would love to reevaluate if this issue ever has a resolution 

<img width="467" alt="Screenshot 2024-04-16 at 10 46 26 AM" src="https://github.com/huggingface/llm-vscode/assets/237454/7d108485-ac9b-41ee-83ac-8caa7687d55c">
<img width="459" alt="Screenshot 2024-04-16 at 11 01 22 AM" src="https://github.com/huggingface/llm-vscode/assets/237454/62e168d4-f4e9-4dad-b1d5-cc34ec787cb1">

**Sytem Data:**

llm-vscode version: v0.2.0

VSCode Info:
Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

MacOS version: 14.4 (23E214)
Processor: Mac M3 Pro (18Gb RAM)

**Comment by onigetoc** [comment] 2024-04-25 21:48
same for me.

**Comment by kidsnz** [comment] 2024-05-02 11:58
<img width="850" alt="Screen Shot 2024-05-02 at 7 53 10 AM" src="https://github.com/huggingface/llm-vscode/assets/95831927/43df9f71-cec5-4cbe-9c6c-8c7170a3eddd">
Same here too.  Should we do a Pro account because of this or is my specs too old?

MacOS version: 10.14.6
VS Code version:1.85.2

**Comment by bkoz** [comment] 2024-05-07 21:50
This fails on both Mac and Linux platforms. Could it be related to the LLM service itself? Perhaps something has changed in the configuration?

**Comment by McPatate** [comment] 2024-05-29 08:16
Service Unavailable either means the backend (in this case https://huggingface.co/docs/api-inference/en/index) is in a degraded state, either that it couldn't load your model.

Imo what happened is that starcoder is not loaded by default anymore given starcoder2 came out and can't be loaded because is too big. When this happens, you either need to change the backend, or change the model your extension is using. We (Hugging Face) could be more clear with what models are loaded manually in the Serverless API.
I've changed the default model configuration to use starcoder2, let me know if when updating the extension you're still facing issues.

**Comment by JShep-tri** [comment] 2024-06-01 20:39
FWIW, I also seem to be having this error on my Linux platform.  Though, not sure if it's user error or related to this.  Essentially my inference endpoint using a fine-tuned version of starcoder2 is throwing `inference api error: Service Unavailable`.  I can confirm my endpoint is operational via the huggingface console.

**Comment by bkoz** [comment] 2024-06-02 23:38
I am able to get the extension working by setting the model ID to **codellama/CodeLlama-13b-hf** and the Config Template to **hf/codellama/CodeLlama-13b-hf**

**Comment by JShep-tri** [comment] 2024-06-03 02:42
I was able to get my extension working as well (user error).  My settings.json is as follows, I had to update the `modelId` to comply with the base model my finetuned model was derived from:
```
{
    "[typescriptreact]": {
        "editor.defaultFormatter": "rvest.vs-code-prettier-eslint"
    },
    "llm.attributionEndpoint": "https://<endpoint-id>.us-east-1.aws.endpoints.huggingface.cloud",
    "cmake.showOptionsMovedNotification": false,
    "llm.modelId": "bigcode/starcoder2-15b",
    "llm.requestBody": {

        "parameters": {
            "max_new_tokens": 60,
            "temperature": 0.2,
            "top_p": 0.95
        }
    }
}
```

**Comment by McPatate** [comment] 2024-06-03 15:22
@JShep-tri `attributionEndpoint` is unrelated to the actual endpoint being called for completions. It is used to check if selected code is present in a dataset or not with the `Llm: Show Code Attribution` command.

In your case, you will need to do the following to configure `llm-vscode` to hit your endpoint:
```js
{
    "llm.url": "https://<endpoint-id>.us-east-1.aws.endpoints.huggingface.cloud",
    "llm.backend": "tgi", // or whatever is powering inference, I assume it is TGI given you are using our dedicated inference solution
    "llm.modelId": "bigcode/starcoder2-15b",
    "llm.requestBody": {
        "parameters": {
            "max_new_tokens": 60,
            "temperature": 0.2,
            "top_p": 0.95
        }
    }
}
```
I'd suggest you take a look at [`llm.nvim`](https://github.com/huggingface/llm.nvim)'s README as it's explained a bit better than llm-vscode's README (and it is quite similar).
The reason why you got it working is that by default the backend is `huggingface` and it will use the model id to route the request accordingly to the correct serverless endpoint.

Let me know if you need additional help, in the meantime I'll close the issue.

**Closed by McPatate** 2024-06-03 15:22 UTC

**Comment by JShep-tri** [comment] 2024-06-03 18:47
Thank you @McPatate, that worked!
